s = str(input("Введите строку: "))
s = s.replace('\t', ' ')
s = s.replace('\n', ' ')
s = s.replace('"', '')
s = s.replace(',', '')
s = s.replace('.', '')
s = s.replace(':', '')
s = s.replace(';', '')
s = s.replace('!', '')
s = s.replace('?', '')
print(s)
